.TH KAZAM "1" "January 2013" "kazam" "User Commands"
.SH NAME
Kazam \- Screen recording and capturing program.
.SH SYNOPSIS
.B kazam [\-h] [\-\-debug] [\-\-silent] [\-\-nosound] [\-\-test] [\-v] [\-f] [\-a] [\-s] [\-w] [\-p] [\-g] [\-x]
.PP
.SH DESCRIPTION
\fBKazam\fR provides a well designed and easy to use interface for capturing
screencasts and screenshots. It can record desktop video and multiple audio
streams simultaneously with control over audio levels and the screen region
being captured.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-debug\fR
enable debug mode
.TP
\fB\-\-silent\fR
silent start, no UI shown
.TP
\fB\-\-nosound\fR
disable PulseAudio
.TP
\fB\-\-test\fR
generate test video signal
.TP
\fB\-v\fR, \fB\-\-version\fR
show program's version number and exit
.TP
\fB\-f\fR, \fB\-\-fullscreen\fR
instant screenshot of a full screen
.TP
\fB\-a\fR, \fB\-\-area\fR
instant screenshot of a preselected screen area
.TP
\fB\-s\fR, \fB\-\-select\fR
instant screenshot of a preselected window
.TP
\fB\-w\fR, \fB\-\-window\fR
instant screenshot of an active window
.TP
\fB\-p\fR, \fB\-\-preferences\fR
show preferences window
.TP
\fB\-g\fR, \fB\-\-godmode\fR
god mode of capture
.TP
\fB\-x\fR, \fB\-\-instance\fR
spawn new instance

.SH AUTHOR
The following people worked on this software:

Matthew Paul Thomas \- Design, Testing
.TP
Michael Vogt \- Coding
.TP
Sebastian Heinlein \- Widgets
.TP
Matthew McGowan \- Pathbar, Widgets, Fixes, Coding
.TP
Andrew Higginson \- Coding, Artwork, Bughelp, Design
.TP
K.Vishnoo Charan Reddy \- Artwork, Bughelp, Design
.TP
Gary Lasker \- Coding
.TP
David Klasinc \- Coding
.TP
Georgi Karavasilev \- Design, Testing
.TP
Alan Pope \- Testing
.TP
Ken VanDine \- Packaging
.TP
Frank Souza \- Design
.TP
This manpage was written by Andrew Starr-Bochicchio <asb@debian.org> for the Debian project.

.SH SEE ALSO
Website: https://launchpad.net/kazam
